version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - "touch .npmignore"
      - "npm -g install gulp"
  pre_build:
    commands:
      - "npm install --frozen-lockfile --production"
  build:
    commands:
      - "npm run pretest"
  post_build:
    commands:
      - "npm run deploy"
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: no
cache:
  paths:
    - ".cache/*"
    - "public/*"
